/*
Navicat MySQL Data Transfer

Source Server         : 115.159.85.171
Source Server Version : 50642
Source Host           : 115.159.85.171:3306
Source Database       : shop

Target Server Type    : MYSQL
Target Server Version : 50642
File Encoding         : 65001

Date: 2018-11-15 19:05:21
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for TB_ADMIN
-- ----------------------------
DROP TABLE IF EXISTS `TB_ADMIN`;
CREATE TABLE `TB_ADMIN` (
  `ADMIN_ID` varchar(64) NOT NULL,
  `ADMIN_NAME` varchar(64) NOT NULL,
  `ADMIN_PASS` varchar(255) NOT NULL,
  PRIMARY KEY (`ADMIN_ID`,`ADMIN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for TB_GOODS
-- ----------------------------
DROP TABLE IF EXISTS `TB_GOODS`;
CREATE TABLE `TB_GOODS` (
  `GOODS_ID` varchar(64) NOT NULL,
  `GOODS_NAME` varchar(32) NOT NULL,
  `GOODS_TYPE` varchar(64) DEFAULT NULL,
  `GOOS_STATU` int(11) DEFAULT '1',
  `GOODS_SEE` bigint(20) DEFAULT '0',
  `GOODS_MIN_PRICE` int(64) DEFAULT '0',
  `GOODS_MAX_PRICE` int(64) DEFAULT '0',
  `GOODS_DESC` varchar(255) DEFAULT '',
  `GOODS_URL` varchar(255) DEFAULT '',
  `GOODS_IMG` varchar(64) DEFAULT '',
  `GOODS_INDEX` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`GOODS_ID`),
  KEY `GOODS_INDEX` (`GOODS_INDEX`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for TB_GOODS_TOP
-- ----------------------------
DROP TABLE IF EXISTS `TB_GOODS_TOP`;
CREATE TABLE `TB_GOODS_TOP` (
  `GOODS_ID` varchar(64) NOT NULL,
  `GOODS_NAME` varchar(32) NOT NULL,
  `GOODS_TYPE` varchar(64) DEFAULT NULL,
  `GOOS_STATU` int(11) DEFAULT '1',
  `GOODS_SEE` bigint(20) DEFAULT '0',
  `GOODS_MIN_PRICE` int(64) DEFAULT '0',
  `GOODS_MAX_PRICE` int(64) DEFAULT '0',
  `GOODS_DESC` varchar(255) DEFAULT '',
  `GOODS_URL` varchar(255) DEFAULT '',
  `GOODS_IMG` varchar(64) DEFAULT '',
  PRIMARY KEY (`GOODS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for TB_LOG
-- ----------------------------
DROP TABLE IF EXISTS `TB_LOG`;
CREATE TABLE `TB_LOG` (
  `LOG_ID` varchar(64) NOT NULL,
  `LOG_IP` varchar(32) DEFAULT NULL,
  `LOG_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `LOG_AREAR` varchar(255) DEFAULT '',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for TB_SEE
-- ----------------------------
DROP TABLE IF EXISTS `TB_SEE`;
CREATE TABLE `TB_SEE` (
  `SEE_SIZE` bigint(20) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for TB_SUBNET
-- ----------------------------
DROP TABLE IF EXISTS `TB_SUBNET`;
CREATE TABLE `TB_SUBNET` (
  `NET_ID` varchar(64) COLLATE utf8_bin NOT NULL,
  `NET_URL` varchar(128) COLLATE utf8_bin NOT NULL,
  `GOODS_ID` varchar(64) COLLATE utf8_bin NOT NULL,
  `NET_STATUS` smallint(255) DEFAULT '1',
  `NET_SEE` int(11) DEFAULT '0',
  `NET_NAME` varchar(64) COLLATE utf8_bin DEFAULT '',
  PRIMARY KEY (`NET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
-- Table structure for TB_TYPE
-- ----------------------------
DROP TABLE IF EXISTS `TB_TYPE`;
CREATE TABLE `TB_TYPE` (
  `TYPE_ID` varchar(64) NOT NULL COMMENT '主键',
  `TYPE_NAME` varchar(64) NOT NULL COMMENT '类型名称',
  PRIMARY KEY (`TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- View structure for VW_ALL_GOODS
-- ----------------------------
DROP VIEW IF EXISTS `VW_ALL_GOODS`;
CREATE  VIEW `VW_ALL_GOODS` AS select `TB_GOODS`.`GOODS_ID` AS `GOODS_ID`,`TB_GOODS`.`GOODS_NAME` AS `GOODS_NAME`,`TB_GOODS`.`GOODS_TYPE` AS `GOODS_TYPE`,`TB_GOODS`.`GOOS_STATU` AS `GOOS_STATU`,`TB_GOODS`.`GOODS_SEE` AS `GOODS_SEE`,`TB_GOODS`.`GOODS_MIN_PRICE` AS `GOODS_MIN_PRICE`,`TB_GOODS`.`GOODS_MAX_PRICE` AS `GOODS_MAX_PRICE`,`TB_GOODS`.`GOODS_DESC` AS `GOODS_DESC`,`TB_GOODS`.`GOODS_URL` AS `GOODS_URL`,`TB_GOODS`.`GOODS_IMG` AS `GOODS_IMG`,`TB_TYPE`.`TYPE_NAME` AS `TYPE_NAME`,`TB_TYPE`.`TYPE_ID` AS `TYPE_ID`,`TB_GOODS`.`GOODS_INDEX` AS `GOODS_INDEX` from (`TB_GOODS` join `TB_TYPE`) where (`TB_TYPE`.`TYPE_ID` = `TB_GOODS`.`GOODS_TYPE`) order by `TB_GOODS`.`GOODS_INDEX` ;

-- ----------------------------
-- View structure for VW_ALL_GOODS_TOP
-- ----------------------------
DROP VIEW IF EXISTS `VW_ALL_GOODS_TOP`;
CREATE  VIEW `VW_ALL_GOODS_TOP` AS select `TB_TYPE`.`TYPE_NAME` AS `TYPE_NAME`,`TB_TYPE`.`TYPE_ID` AS `TYPE_ID`,`TB_GOODS_TOP`.`GOODS_ID` AS `GOODS_ID`,`TB_GOODS_TOP`.`GOODS_NAME` AS `GOODS_NAME`,`TB_GOODS_TOP`.`GOODS_TYPE` AS `GOODS_TYPE`,`TB_GOODS_TOP`.`GOOS_STATU` AS `GOOS_STATU`,`TB_GOODS_TOP`.`GOODS_SEE` AS `GOODS_SEE`,`TB_GOODS_TOP`.`GOODS_MIN_PRICE` AS `GOODS_MIN_PRICE`,`TB_GOODS_TOP`.`GOODS_MAX_PRICE` AS `GOODS_MAX_PRICE`,`TB_GOODS_TOP`.`GOODS_DESC` AS `GOODS_DESC`,`TB_GOODS_TOP`.`GOODS_URL` AS `GOODS_URL`,`TB_GOODS_TOP`.`GOODS_IMG` AS `GOODS_IMG` from (`TB_TYPE` join `TB_GOODS_TOP`) where (`TB_TYPE`.`TYPE_ID` = `TB_GOODS_TOP`.`GOODS_TYPE`) ;

-- ----------------------------
-- View structure for VW_ALL_SUBNET
-- ----------------------------
DROP VIEW IF EXISTS `VW_ALL_SUBNET`;
CREATE  VIEW `VW_ALL_SUBNET` AS select `TB_SUBNET`.`NET_ID` AS `NET_ID`,`TB_SUBNET`.`NET_URL` AS `NET_URL`,`TB_SUBNET`.`GOODS_ID` AS `GOODS_ID`,`TB_SUBNET`.`NET_STATUS` AS `NET_STATUS`,`VW_BOTH_GOODS`.`GOODS_NAME` AS `GOODS_NAME`,`VW_BOTH_GOODS`.`GOODS_TYPE` AS `GOODS_TYPE`,`VW_BOTH_GOODS`.`GOOS_STATU` AS `GOOS_STATU`,`VW_BOTH_GOODS`.`GOODS_SEE` AS `GOODS_SEE`,`VW_BOTH_GOODS`.`GOODS_MIN_PRICE` AS `GOODS_MIN_PRICE`,`VW_BOTH_GOODS`.`GOODS_MAX_PRICE` AS `GOODS_MAX_PRICE`,`VW_BOTH_GOODS`.`GOODS_DESC` AS `GOODS_DESC`,`VW_BOTH_GOODS`.`GOODS_URL` AS `GOODS_URL`,`VW_BOTH_GOODS`.`GOODS_IMG` AS `GOODS_IMG`,`VW_BOTH_GOODS`.`TYPE_NAME` AS `TYPE_NAME`,`VW_BOTH_GOODS`.`TYPE_ID` AS `TYPE_ID`,`TB_SUBNET`.`NET_SEE` AS `NET_SEE` from (`TB_SUBNET` join `VW_BOTH_GOODS` on((`VW_BOTH_GOODS`.`GOODS_ID` = `TB_SUBNET`.`GOODS_ID`))) ;

-- ----------------------------
-- View structure for VW_BOTH_GOODS
-- ----------------------------
DROP VIEW IF EXISTS `VW_BOTH_GOODS`;
CREATE  VIEW `VW_BOTH_GOODS` AS select `VW_ALL_GOODS_TOP`.`GOODS_ID` AS `GOODS_ID`,`VW_ALL_GOODS_TOP`.`GOODS_NAME` AS `GOODS_NAME`,`VW_ALL_GOODS_TOP`.`GOODS_TYPE` AS `GOODS_TYPE`,`VW_ALL_GOODS_TOP`.`GOOS_STATU` AS `GOOS_STATU`,`VW_ALL_GOODS_TOP`.`GOODS_SEE` AS `GOODS_SEE`,`VW_ALL_GOODS_TOP`.`GOODS_MIN_PRICE` AS `GOODS_MIN_PRICE`,`VW_ALL_GOODS_TOP`.`GOODS_MAX_PRICE` AS `GOODS_MAX_PRICE`,`VW_ALL_GOODS_TOP`.`GOODS_DESC` AS `GOODS_DESC`,`VW_ALL_GOODS_TOP`.`GOODS_URL` AS `GOODS_URL`,`VW_ALL_GOODS_TOP`.`GOODS_IMG` AS `GOODS_IMG`,`VW_ALL_GOODS_TOP`.`TYPE_NAME` AS `TYPE_NAME`,`VW_ALL_GOODS_TOP`.`TYPE_ID` AS `TYPE_ID` from `VW_ALL_GOODS_TOP` union select `VW_ALL_GOODS`.`GOODS_ID` AS `GOODS_ID`,`VW_ALL_GOODS`.`GOODS_NAME` AS `GOODS_NAME`,`VW_ALL_GOODS`.`GOODS_TYPE` AS `GOODS_TYPE`,`VW_ALL_GOODS`.`GOOS_STATU` AS `GOOS_STATU`,`VW_ALL_GOODS`.`GOODS_SEE` AS `GOODS_SEE`,`VW_ALL_GOODS`.`GOODS_MIN_PRICE` AS `GOODS_MIN_PRICE`,`VW_ALL_GOODS`.`GOODS_MAX_PRICE` AS `GOODS_MAX_PRICE`,`VW_ALL_GOODS`.`GOODS_DESC` AS `GOODS_DESC`,`VW_ALL_GOODS`.`GOODS_URL` AS `GOODS_URL`,`VW_ALL_GOODS`.`GOODS_IMG` AS `GOODS_IMG`,`VW_ALL_GOODS`.`TYPE_NAME` AS `TYPE_NAME`,`VW_ALL_GOODS`.`TYPE_ID` AS `TYPE_ID` from `VW_ALL_GOODS` ;
